apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hep-programming-hints.fullname" . }}-fast-mcp-secret
  labels:
    {{- include "hep-programming-hints.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.secret.token | b64enc }}